default_tables = {
    'Colors' : [
        {'color_id' : '1', 'color_name' : 'Red'},
        {'color_id' : '2', 'color_name' : 'Orange'},
        {'color_id' : '3', 'color_name' : 'Yellow'},
        {'color_id' : '4', 'color_name' : 'Green'},
        {'color_id' : '5', 'color_name' : 'Blue'},
        {'color_id' : '6', 'color_name' : 'Indigo'},
        {'color_id' : '7', 'color_name' : 'Violet'},
    ],
    'Fabrics' : [
        {'fabric_id' : '1', 'fabric_name' : 'Cotton'},
        {'fabric_id' : '2', 'fabric_name' : 'Linen'},
        {'fabric_id' : '3', 'fabric_name' : 'Hemp'},
        {'fabric_id' : '4', 'fabric_name' : 'Wool'},
        {'fabric_id' : '5', 'fabric_name' : 'Cashmere'},
        {'fabric_id' : '6', 'fabric_name' : 'Silk'},
        {'fabric_id' : '7', 'fabric_name' : 'Polyester'},
        {'fabric_id' : '8', 'fabric_name' : 'Nylon'},
        {'fabric_id' : '9', 'fabric_name' : 'Spandex'},
        {'fabric_id' : '10', 'fabric_name' : 'Acrylic'},
    ],
    'Brands' : [
        {'brand_id': '1', 'brand_name': 'Nike'},
        {'brand_id': '2', 'brand_name': 'Adidas'},
        {'brand_id': '3', 'brand_name': 'Zara'},
        {'brand_id': '4', 'brand_name': 'H&M'},
        {'brand_id': '5', 'brand_name': 'Uniqlo'},
        {'brand_id': '6', 'brand_name': 'Levi\'s'},
        {'brand_id': '7', 'brand_name': 'Gucci'},
        {'brand_id': '8', 'brand_name': 'Louis Vuitton'},
        {'brand_id': '9', 'brand_name': 'Under Armour'},
        {'brand_id': '10', 'brand_name': 'Puma'},
    ],
    'Sizes' : [
        {'size_id' : '1', 'size_name' : 'XS'},
        {'size_id' : '2', 'size_name' : 'S'},
        {'size_id' : '3', 'size_name' : 'M'},
        {'size_id' : '4', 'size_name' : 'L'},
        {'size_id' : '5', 'size_name' : 'XL'},
        {'size_id' : '6', 'size_name' : '26'},
        {'size_id' : '7', 'size_name' : '27'},
        {'size_id' : '8', 'size_name' : '28'},
        {'size_id' : '9', 'size_name' : '29'},
        {'size_id' : '10', 'size_name' : '30'},
        {'size_id' : '11', 'size_name' : '31'},
        {'size_id' : '12', 'size_name' : '32'},
        {'size_id' : '13', 'size_name' : '33'},
        {'size_id' : '14', 'size_name' : '34'},
        {'size_id' : '15', 'size_name' : '35'},
    ],
    'Clothing Types' : [
        {'type_id' : '1', 'type_name' : 'XS'},
        {'type_id' : '2', 'type_name' : 'S'},
        {'type_id' : '3', 'type_name' : 'M'},
        {'type_id' : '4', 'type_name' : 'L'},
        {'type_id' : '5', 'type_name' : 'XL'},
        {'type_id' : '6', 'type_name' : '26'},
        {'type_id' : '7', 'type_name' : '27'},
        {'type_id' : '8', 'type_name' : '28'},
    ],
}
